name: Tests on staging on "main" branch repo pull request

on:
  pull_request_target:
    types: [opened, synchronize]
    branches:
      - 'main'
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.jsx'
      - '**/*.tsx'
      - '**/*.cjs'
      - '**/*.mjs'
      - '**/*.json'
      - '**/pnpm-lock.yaml'
      #- '!**/package.json'
      - '!**/.eslintrc.json'
      - '!**/.prettierrc.json'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: CI/CD

    strategy:
      matrix:
        node-version: ['lts/*']

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use latest pnpm
        uses: pnpm/action-setup@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
      - name: Run e2e tests on staging
        run: |
          pnpm run test-e2e
